# Exercício 1 - Soma de Matrizes
Programa em Python que soma duas matrizes de mesmo tamanho

In [13]:
#Criando duas matrizes
matriz1 = [[1,2,3], [0,1,4], [5,6,0]]
matriz2 = [[5,2,8],[3,1,2],[7,0,2]]

In [3]:
print(matriz1)

[[1, 2, 3], [0, 1, 4], [5, 6, 0]]


In [4]:
print(matriz2)

[[5, 2, 8], [3, 1, 2], [7, 0, 2]]


In [7]:
#Resolução com Numpy
import numpy as np
def soma_matrizes_versao1(m1,m2):
  return np.array(m1) + np.array(m2)

In [8]:
soma_matrizes_versao1(matriz1,matriz2)

array([[ 6,  4, 11],
       [ 3,  2,  6],
       [12,  6,  2]])

In [9]:
# Resolução sem Numpy

def soma_matrizes(matriz1, matriz2):
    # Verificação do tamanho das matrizes
    if len(matriz1) != len(matriz2) or len(matriz1[0]) != len(matriz2[0]):
        raise ValueError("As matrizes devem ter o mesmo tamanho")

    # Lista vazia que armazena o resultado
    matriz_resultado = []

    # Loop
    # O primeiro loop percorre cada linha das matrizes e o segundo loop cada coluna, após isso é somado e
    # adiciona o resultado à lista 'linha'
    for i in range(len(matriz1)):
        linha = []
        for j in range(len(matriz1[0])):
            linha.append(matriz1[i][j] + matriz2[i][j])
        # Armazenando o resultado
        matriz_resultado.append(linha)

    return matriz_resultado

# Chamando a função e imprimindo o resultado
resultado = soma_matrizes(matriz1, matriz2)
for linha in resultado:
    print(linha)



[6, 4, 11]
[3, 2, 6]
[12, 6, 2]


# Exercicio 2 - Multiplicação de Matrizes


Implementar uma função em python multiplicando duas matrizes

In [20]:
#Sem Numpy

def multiplicacao_matrizes(m1, m2):
    # Verificação de compatibilidade
    if len(m1[0]) != len(m2):
        return "As matrizes não são compatíveis para a multiplicação"

    # Inicialização da Matriz resultante
    resultado = []

    # Interação da linha
    for i in range(len(m1)):
        linha = []

        # Interação da coluna
        for j in range(len(m2[0])):
            soma = 0

            # Calculo do produto escalar
            for k in range(len(m2)):
                soma += m1[i][k] * m2[k][j]

            # Construção da linha da matriz resultante
            linha.append(soma)

        # Adição da linha da matriz resultante
        resultado.append(linha)

    # Retorno da matriz
    return resultado

#Resultado
multiplicacao_matrizes(matriz1, matriz2)


[[32, 4, 18], [31, 1, 10], [43, 16, 52]]

In [24]:
#Com Numpy versao 1
import numpy as np

# Definição da função
def multiplicacao_matrizes(A, B):
    
    # Conversão para Array Numpy
    A_np = np.array(A)
    B_np = np.array(B)

    # Multiplicação da matriz
    return np.dot(A_np, B_np)

#Resultado
multiplicacao_matrizes(matriz1, matriz2)


array([[32,  4, 18],
       [31,  1, 10],
       [43, 16, 52]])

In [25]:
#Com numpy versao 2

def multiplicacao_matrizes(m1,m2):
  return np.dot(m1,m2)

#Resultado
multiplicacao_matrizes(matriz1,matriz2)


array([[32,  4, 18],
       [31,  1, 10],
       [43, 16, 52]])